name: Build and Push Docker Images

on:
  push:  # Runs on every push (tagged or not)
    branches:
      - master  # Also runs when pushing to the master branch
    tags:
      - '*'  # Runs when a tag is pushed
  workflow_dispatch:  # Allows manual execution

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine Docker Tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "GIT_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build and Push vllm_server Image
        uses: docker/build-push-action@v5
        with:
          context: ./vllm_server
          file: ./vllm_server/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/vllm_server:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/vllm_server:${{ env.GIT_TAG }}

      - name: Build and Push gradio_app Image
        uses: docker/build-push-action@v5
        with:
          context: ./gradio_app
          file: ./gradio_app/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gradio_app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/gradio_app:${{ env.GIT_TAG }}
